### ISSUE TITLE
BoardService 부분

### ISSUE THREAD

**Issue by kimyounggeul** [jwywoo/SimpleBoardAuth#3]
boardCreate 부분, boardUpdate 부분, boardDelet 부분에
동일한 코드를 tokenValidation 로 만들어 넣어준것이 깔끔하고 보기좋았습니다

`private Claims tokenValidation(HttpServletRequest req) {
        String givenToken = jwtUtil.getTokenFromRequest(req);
        givenToken = jwtUtil.substringToken(givenToken);
        if (!jwtUtil.validateToken(givenToken)) throw new IllegalArgumentException("Invalid User Credentials");
        return jwtUtil.getUserInfoFromToken(givenToken);
`

**Comment by jwywoo** [comment]
Good
