### ISSUE TITLE
 BoardController 부분

### ISSUE THREAD

**Issue by rokmc1249** [jwywoo/SimpleBoardAuth#4]
`   public ResponseEntity<BoardResponseDto> boardCreate(@RequestBody BoardRequestDto requestDto, HttpServletRequest req)`

  HttpServletRequest을 이용해 직접 토큰을 가져와서 담은 것 같은데 그 점이 저희가 구현한 부분이랑 달라서 좀 더 코드도 안길어 보이고 깔끔해보이네요.

**Comment by jwywoo** [comment]
GOOD
