### ISSUE TITLE
BoardService 부분 

### ISSUE THREAD

**Issue by rokmc1249** [jwywoo/SimpleBoardAuth#5]
`private Claims tokenValidation(HttpServletRequest req) {
        String givenToken = jwtUtil.getTokenFromRequest(req);
        givenToken = jwtUtil.substringToken(givenToken);
        if (!jwtUtil.validateToken(givenToken)) throw new IllegalArgumentException("Invalid User Credentials");
            return jwtUtil.getUserInfoFromToken(givenToken);
    }`
    
    
delete, update, put할 때 토큰의 유효성 검사가 매번 이뤄지는데 따로 메서드로 빼서 코드의 간결하게 만든 점이 인상깊어요. 근데 HttpServletRequest을 통해 직접 JWT 순수 토큰을 받아 오시는 것 같은데 만약 직접 쿠키의 value를 받아 올 경우는 substringToken 메서드를 통해 토 토큰이 이미 순수하게 포함되어 있지 않을 때만 추출하기 위해 사용되는건데  따로 substringToken 메서드를 사용한 이유가 궁금해요!

**Comment by jwywoo** [comment]
Good
